; ---------------- file resources --------------------

directory    RT_ICON,icons,\
             RT_GROUP_ICON,group_icons,\
             RT_VERSION,versions

resource icons		,1,LANG_NEUTRAL,icon_data
resource group_icons	,17,LANG_NEUTRAL,main_icon
resource versions	,1,LANG_NEUTRAL,version

icon main_icon,icon_data,ICON

versioninfo version,VOS__WINDOWS32,VFT_APP,VFT2_UNKNOWN,LANG_ENGLISH+SUBLANG_DEFAULT,0,\
                                 'FileDescription','Blitz 3D FASM Application',\
                                 'FileVersion','1.0'

